spring:
  profiles:
    active: dev
    include: quartz
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
mybatis-plus:
  mapper-locations: classpath*:com/wq/money/**/mapper/xml/*Mapper.xml
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
check-session-token: token
jwt:
  header: Authorization
  secret: mySecret
  #token失效时间
  expiration: 6048000
  #登录失效时间（多长时间不操作重新登录）
  expireTime: 1800
  route.authentication.path: /auth
  route.authentication.refresh: /refresh
email:
  nickName: 系统管理员
  userName: 18210207783@163.com
  passWord: RGTDXQRUYDQNWMBO
  proToCol: smtp
  host: smtp.163.com
  port: 25